services:

  arming: "/mavros/cmd/arming"
  takeoff: "/mavros/cmd/takeoff"
  setmode: "/mavros/set_mode"
  land: "/mavros/cmd/land"
  set_stream_rate: "/mavros/set_stream_rate"

custom_modes:
  - "STABILIZE"
  - "ACRO"
  - "ALT_HOLD"
  - "AUTO"
  - "GUIDED"
  - "LOITER"
  - "RTL"
  - "CIRCLE"
  - "POSITION"
  - "LAND"
  - "OF_LOITER"
  - "DRIFT"
  - "SPORT"
  - "FLIP"
  - "AUTOTUNE"
  - "POSHOLD"
  - "BRAKE"
  - "THROW"
  - "AVOID_ADSB"
  - "GUIDED_NOGPS"
